### ISSUE TITLE
Ionic Side Bar Menu

### ISSUE THREAD

**Issue by nspangler** [Urigo/meteor-ionic#34]
Hey great package! I am having trouble integrating ionic and creating a basic side bar menu with the newest meteor and packages:

![screen shot 2015-01-14 at 5 35 30 pm](https://cloud.githubusercontent.com/assets/5549886/5761216/3a80b2be-9c97-11e4-96a0-ccb6ae4052b6.png)

index.html:

    <body>
        <div>

        <ion-side-menus>
            
            <ion-side-menu-content>
                <ion-header-bar class="bar-dark">
                    <h1 class="title">Todo</h1>
                </ion-header-bar>
                <ion-content>
                </ion-content>
            </ion-side-menu-content>

            
            <ion-side-menu side="left">
                <ion-header-bar class="bar-dark">
                    <h1 class="title">Projects</h1>
                </ion-header-bar>
            </ion-side-menu>

        </ion-side-menus>

       </div>
     </body>

app.js

      if (Meteor.isClient) {

        var app = angular.module('todo', ['angular-meteor', 'ionic'], function($interpolateProvider) {
           $interpolateProvider.startSymbol('[[');
           $interpolateProvider.endSymbol(']]');
       });

        app.controller("TodoCtrl", ['$scope', '$collection', '$ionicSideMenuDelegate', function ($scope, $collection, $ionicSideMenuDelegate) {

        $scope.toggleProjects = function () {
              $ionicSideMenuDelegate.toggleLeft();
         };
       }]);

     }

The result is this:
![screen shot 2015-01-14 at 5 32 59 pm](https://cloud.githubusercontent.com/assets/5549886/5761218/3f785d3a-9c97-11e4-95bd-1c748299d032.png)

**Comment by Urigo** [comment]
Why do you change the symbols?
There is no need to do that anymore, take a look at https://github.com/Urigo/angular-meteor#routing

@netanelgilad I think we should update the Ionic-example repo

**Comment by nspangler** [comment]
@Urigo if I don't use the `$interpolateProvider` I get this :
![screen shot 2015-01-15 at 9 59 32 am](https://cloud.githubusercontent.com/assets/5549886/5762183/a27ae3ac-9c9d-11e4-82e6-2f55ceb73038.png)

**Comment by netanelgilad** [comment]
@nspangler with angular-metoer 0.6.0 you can work with regular curly braces bindings {{ }}.
But in order to do that correctly you need to have your templates in a file ending with .tpl.
So in your case do the following: 

index.html:
```html
<body>
<ng-include src="'client/index.tpl'"></ng-include>
 </body>
```

index.tpl:
```html
    <div>

    <ion-side-menus>
        <!-- Center content -->
        <ion-side-menu-content>
            <ion-header-bar class="bar-dark">
                <h1 class="title">Todo</h1>
            </ion-header-bar>
            <ion-content>
            </ion-content>
        </ion-side-menu-content>

        <!-- Left menu -->
        <ion-side-menu side="left">
            <ion-header-bar class="bar-dark">
                <h1 class="title">Projects</h1>
            </ion-header-bar>
        </ion-side-menu>

    </ion-side-menus>

   </div>
```

@Urigo Yep, need to update. Will do that this weekend..

**Comment by Urigo** [comment]
I re-wrote the example to work now, @netanelgilad please add me to the repo so I can push

**Comment by Urigo** [comment]
Pushed. 
Please check and re-open in case of a problem

**Comment by rrwexpert** [comment]
Hi Urigo,

I really enjoy all of your tutorials and appreciated everyone efforts.
I had download sample app "sidemenu-meteor" and it works great, but the structure of this sample app is quite different than most of your tutorial app.

I am having difficulty transforming it to the structure that you have. For example, the sidemenu-meteor has only one controllers.js file under the client folder /client/controllers.js and the client/lib/app.js codes are way different than your tutorrial/sample file.

do you have an updated version of your Simple ToDos app or WhatsApp or Socially angular-meteor tutorial that include ionic side-menu bar?

I have attached the sample code sidemenu-meteor.zip file to this post. Please advise me on how to convert the /client/app.js to work similar to your tutorials and also being able have separate controller for each html file - such as: abc.html, abc.controller.js, a single client/scripts/routes.js and a single client/lib/app.js files.

Bellow is the content of the /client/lib/app.js file of the sidemenu-meteor sample:

---

// Ionic Starter App

// angular.module is a global place for creating, registering and retrieving Angular modules
// 'starter' is the name of this angular module example (also set in a <body> attribute in index.html)
// the 2nd parameter is an array of 'requires'
// 'starter.controllers' is found in controllers.js

```
Meteor.startup(function ()
{    
  angular.bootstrap(document, ['starter']);
});
```

angular.module('starter', ['angular-meteor','ionic', 'starter.controllers'])

.run(['$ionicPlatform',function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
  });
}])

.config(['$stateProvider', '$urlRouterProvider',function($stateProvider, $urlRouterProvider){

  $stateProvider

```
.state('app', {
  url: "/app",
  abstract: true,
  templateUrl:'client/templates/menu.ng.html',
  controller: 'AppCtrl'
})

.state('app.search', {
  url: "/search",
  views: {
    'menuContent' :{
      templateUrl:'client/templates/search.ng.html'
    }
  }
})

.state('app.browse', {
  url: "/browse",
  views: {
    'menuContent' :{
      templateUrl:'client/templates/browse.ng.html',
    }
  }
})
.state('app.playlists', {
  url: "/playlists",
  views: {
    'menuContent' :{
      templateUrl:'client/templates/playlists.ng.html',
      controller: 'PlaylistsCtrl'
    }
  }
})

.state('app.single', {
  url: "/playlists/:playlistId",
  views: {
    'menuContent' :{
      templateUrl:'client/templates/playlist.ng.html',
      controller: 'PlaylistCtrl'
    }
  }
});
```

  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/app/playlists');
}]);
[sidemenu-meteor.zip](https://github.com/Urigo/meteor-ionic/files/402807/sidemenu-meteor.zip)

Thanks,

BNguyen

**Comment by Urigo** [comment]
@rrwexpert this repo is outdated and deprecated.

You should use Ionic directly from npm or bower - here are examples on how to do this:

http://www.angular-meteor.com/tutorials/whatsapp/
http://www.angular-meteor.com/tutorials/socially/angular1/ionic
http://www.angular-meteor.com/tutorials/socially/angular2/ionic
